#!/bin/bash

loop(){
	local TIMES="$1"
	shift
	for i in $(seq 1 $TIMES)
	do
		eval "$@"
	done
}
export -f loop

# keypresses
pgup(){
	printf '\033[5~'
}

pgdn(){
	printf '\033[6~'
}

# the right key
keyr(){
	printf '\033[C'
}
export -f pgup pgdn keyr

# BBS functions
switch(){
	printf 's%s\n' "$1"
}

view(){
	printf 's\n%s\n' "$1"
}

p(){
	printf 'k'
}

n(){
	printf 'j'
}

q(){
	printf 'q'
}

last(){
	printf '$'
}

enter(){
	printf '\n'
}

reenter(){
	printf 'q\n\n'
}

redraw(){
	printf '\014'
}

post(){
	printf '\020'
	if [ -n "$1" ]; then
		echo "$1"
	fi
}

save(){
	printf '\027'
}

bye(){
	printf '!\n\n'
}
export -f switch view p n q last enter reenter redraw post save bye

/usr/bin/env PS1='(bbs)' bash --norc > $1

