#!/bin/bash

if [ ! -n "$1" ]; then
	printf 'usage: ./keysnd <BBS FIFO> | <SSH command> \n' 1>&2
	exit 1
fi

FIFO="$1"
mkfifo $FIFO
# Thanks to Invader@newsmth to provide this method
sleep 1000d > $FIFO &
# FIXME: how to use sth like cat that can run forever?
# use set -m will solve, but leads to other problems
#cat > $FIFO &
WCATPID=$!
cat $FIFO &
CATPID=$!
echo "write cat pid:$WCATPID real cat pid:$CATPID" 1>&2

clean_up(){
	rm -f $FIFO
	kill $WCATPID
	kill $CATPID
	exit
}

anti_idle(){
    printf '\000'
}

trap 'clean_up' 1 2 3 6 9 15
while true
do
    sleep 120
    anti_idle
done


